name: YumehamaPlugin
main: testPack.Main
version: 1.0
commands:
  giveToken:
   description: give token
   usage: /giveToken
  door:
   description: set door
   usage: /door
  증표:
   description: 증표선택
   usage: /증표
api-version: 1.12