name: YumehamaPlugin
main: testPack.Main
version: 1.0
commands:
  redteam:
   description: red team title change
   usage: /redteam
  blueteam:
   description: blue team title change
   usage: /blueteam
  giveToken:
   description: blue team title change
   usage: /givetoken:
  killme:
   description: blue team title change
   usage: /killme
api-version: 1.12